// Translations for supported languages
const translations = {
    en: {
      languageSettingsTitle: "Language Settings",
      languageSettingsDescription: "Change the language preferences for your TekRide account.",
      selectLanguageTitle: "Select Your Preferred Language",
      selectLanguageDescription: "Select your preferred language from the dropdown menu below:",
      chooseLanguage: "Choose Language:",
      setLanguage: "Set Language",
      defaultLanguageTitle: "Default Language Settings",
      defaultLanguageDescription: "When you first create an account or complete your initial setup, you can set your default language. This will be the language that appears when you log in for the first time.",
      setDefaultLanguage: "Set Default Language",
      updateLanguageTitle: "Update Language Preferences",
      updateLanguageDescription: "You can update your language preference at any time through the settings page.",
      updateLanguage: "Update Language",
      home: "Home",
      features: "Features",
      about: "About",
      contact: "Contact",
      logo: "TekRide"
    },
    es: {
      languageSettingsTitle: "Configuración de idioma",
      languageSettingsDescription: "Cambia las preferencias de idioma para tu cuenta de TekRide.",
      selectLanguageTitle: "Selecciona tu idioma preferido",
      selectLanguageDescription: "Selecciona tu idioma preferido en el menú desplegable a continuación:",
      chooseLanguage: "Elige idioma:",
      setLanguage: "Establecer idioma",
      defaultLanguageTitle: "Configuración de idioma predeterminado",
      defaultLanguageDescription: "Cuando crees una cuenta o completes la configuración inicial, puedes establecer tu idioma predeterminado. Este será el idioma que aparecerá cuando inicies sesión por primera vez.",
      setDefaultLanguage: "Establecer idioma predeterminado",
      updateLanguageTitle: "Actualizar preferencias de idioma",
      updateLanguageDescription: "Puedes actualizar tu preferencia de idioma en cualquier momento a través de la página de configuración.",
      updateLanguage: "Actualizar idioma",
      home: "Inicio",
      features: "Características",
      about: "Acerca de",
      contact: "Contacto",
      logo: "TekRide"
    },
    fr: {
      languageSettingsTitle: "Paramètres de langue",
      languageSettingsDescription: "Changez les préférences linguistiques pour votre compte TekRide.",
      selectLanguageTitle: "Sélectionnez votre langue préférée",
      selectLanguageDescription: "Sélectionnez votre langue préférée dans le menu déroulant ci-dessous :",
      chooseLanguage: "Choisir la langue:",
      setLanguage: "Définir la langue",
      defaultLanguageTitle: "Paramètres de langue par défaut",
      defaultLanguageDescription: "Lorsque vous créez un compte ou complétez votre configuration initiale, vous pouvez définir votre langue par défaut. Ce sera la langue qui apparaîtra lors de votre première connexion.",
      setDefaultLanguage: "Définir la langue par défaut",
      updateLanguageTitle: "Mettre à jour les préférences linguistiques",
      updateLanguageDescription: "Vous pouvez mettre à jour vos préférences linguistiques à tout moment via la page des paramètres.",
      updateLanguage: "Mettre à jour la langue",
      home: "Accueil",
      features: "Caractéristiques",
      about: "À propos",
      contact: "Contact",
      logo: "TekRide"
    },
    de: {
      languageSettingsTitle: "Spracheinstellungen",
      languageSettingsDescription: "Ändern Sie die Spracheinstellungen für Ihr TekRide-Konto.",
      selectLanguageTitle: "Wählen Sie Ihre bevorzugte Sprache",
      selectLanguageDescription: "Wählen Sie Ihre bevorzugte Sprache aus dem Dropdown-Menü unten:",
      chooseLanguage: "Sprache wählen:",
      setLanguage: "Sprache festlegen",
      defaultLanguageTitle: "Standardspracheinstellungen",
      defaultLanguageDescription: "Wenn Sie ein Konto erstellen oder die erste Einrichtung abschließen, können Sie Ihre Standardsprache festlegen. Dies wird die Sprache sein, die angezeigt wird, wenn Sie sich zum ersten Mal anmelden.",
      setDefaultLanguage: "Standardsprache festlegen",
      updateLanguageTitle: "Spracheinstellungen aktualisieren",
      updateLanguageDescription: "Sie können Ihre Spracheinstellungen jederzeit über die Seite Einstellungen aktualisieren.",
      updateLanguage: "Sprache aktualisieren",
      home: "Startseite",
      features: "Funktionen",
      about: "Über uns",
      contact: "Kontakt",
      logo: "TekRide"
    },
    it: {
      languageSettingsTitle: "Impostazioni della lingua",
      languageSettingsDescription: "Modifica le preferenze linguistiche per il tuo account TekRide.",
      selectLanguageTitle: "Seleziona la tua lingua preferita",
      selectLanguageDescription: "Seleziona la tua lingua preferita dal menu a discesa qui sotto:",
      chooseLanguage: "Scegli la lingua:",
      setLanguage: "Imposta la lingua",
      defaultLanguageTitle: "Impostazioni lingua predefinita",
      defaultLanguageDescription: "Quando crei un account o completi la configurazione iniziale, puoi impostare la tua lingua predefinita. Questa sarà la lingua che verrà visualizzata quando accedi per la prima volta.",
      setDefaultLanguage: "Imposta la lingua predefinita",
      updateLanguageTitle: "Aggiorna le preferenze linguistiche",
      updateLanguageDescription: "Puoi aggiornare la tua preferenza linguistica in qualsiasi momento tramite la pagina delle impostazioni.",
      updateLanguage: "Aggiorna lingua",
      home: "Home",
      features: "Funzionalità",
      about: "Chi siamo",
      contact: "Contatti",
      logo: "TekRide"
    },
    pt: {
      languageSettingsTitle: "Configurações de idioma",
      languageSettingsDescription: "Altere as preferências de idioma para sua conta TekRide.",
      selectLanguageTitle: "Selecione seu idioma preferido",
      selectLanguageDescription: "Selecione seu idioma preferido no menu suspenso abaixo:",
      chooseLanguage: "Escolha o idioma:",
      setLanguage: "Definir idioma",
      defaultLanguageTitle: "Configurações de idioma padrão",
      defaultLanguageDescription: "Quando você criar uma conta ou concluir a configuração inicial, poderá definir seu idioma padrão. Este será o idioma que aparecerá quando você fizer login pela primeira vez.",
      setDefaultLanguage: "Definir idioma padrão",
      updateLanguageTitle: "Atualizar preferências de idioma",
      updateLanguageDescription: "Você pode atualizar suas preferências de idioma a qualquer momento por meio da página de configurações.",
      updateLanguage: "Atualizar idioma",
      home: "Início",
      features: "Funcionalidades",
      about: "Sobre",
      contact: "Contato",
      logo: "TekRide"
    },
    nl: {
      languageSettingsTitle: "Taalinstellingen",
      languageSettingsDescription: "Wijzig de taalvoorkeuren voor uw TekRide-account.",
      selectLanguageTitle: "Selecteer uw voorkeurstaal",
      selectLanguageDescription: "Selecteer uw voorkeurstaal uit het dropdownmenu hieronder:",
      chooseLanguage: "Kies taal:",
      setLanguage: "Stel taal in",
      defaultLanguageTitle: "Standaardtaalinstellingen",
      defaultLanguageDescription: "Wanneer u een account aanmaakt of de eerste keer instelt, kunt u uw standaardtaal instellen. Dit is de taal die wordt weergegeven wanneer u voor het eerst inlogt.",
      setDefaultLanguage: "Stel standaardtaal in",
      updateLanguageTitle: "Werk taalvoorkeuren bij",
      updateLanguageDescription: "U kunt uw taalvoorkeuren op elk moment bijwerken via de instellingenpagina.",
      updateLanguage: "Werk taal bij",
      home: "Startpagina",
      features: "Kenmerken",
      about: "Over ons",
      contact: "Contact",
      logo: "TekRide"
    },
    hi: {
      languageSettingsTitle: "भाषा सेटिंग्स",
      languageSettingsDescription: "अपनी TekRide खाता के लिए भाषा प्राथमिकताएँ बदलें।",
      selectLanguageTitle: "अपनी पसंदीदा भाषा चुनें",
      selectLanguageDescription: "नीचे ड्रॉपडाउन मेनू से अपनी पसंदीदा भाषा चुनें:",
      chooseLanguage: "भाषा चुनें:",
      setLanguage: "भाषा सेट करें",
      defaultLanguageTitle: "डिफ़ॉल्ट भाषा सेटिंग्स",
      defaultLanguageDescription: "जब आप खाता बनाते हैं या प्रारंभिक सेटअप पूरा करते हैं, तो आप अपनी डिफ़ॉल्ट भाषा सेट कर सकते हैं। यह वह भाषा होगी जो पहली बार लॉगिन करते समय दिखाई देगी।",
      setDefaultLanguage: "डिफ़ॉल्ट भाषा सेट करें",
      updateLanguageTitle: "भाषा प्राथमिकताएँ अपडेट करें",
      updateLanguageDescription: "आप अपनी भाषा प्राथमिकताएँ किसी भी समय सेटिंग्स पृष्ठ के माध्यम से अपडेट कर सकते हैं।",
      updateLanguage: "भाषा अपडेट करें",
      home: "मुखपृष्ठ",
      features: "विशेषताएँ",
      about: "हमारे बारे में",
      contact: "संपर्क",
      logo: "TekRide"
    },
    te: {
      languageSettingsTitle: "భాషా సెట్టింగులు",
      languageSettingsDescription: "మీ TekRide ఖాతా కోసం భాషా ఎంపికలను మార్చండి.",
      selectLanguageTitle: "మీ ప్రాధాన్య భాషను ఎంచుకోండి",
      selectLanguageDescription: "క్రింది డ్రాప్‌డౌన్ మెనునుంచి మీ ప్రాధాన్య భాషను ఎంచుకోండి:",
      chooseLanguage: "భాష ఎంచుకోండి:",
      setLanguage: "భాషను సెట్ చేయండి",
      defaultLanguageTitle: "డిఫాల్ట్ భాషా సెట్టింగులు",
      defaultLanguageDescription: "మీరు ఖాతాను సృష్టించినప్పుడు లేదా ప్రారంభ సెటప్ పూర్తి చేసినప్పుడు, మీరు డిఫాల్ట్ భాషను సెట్ చేయవచ్చు. ఇది మీరు మొదటిసారి లాగిన్ చేసినప్పుడు ప్రదర్శించే భాష అవుతుంది.",
      setDefaultLanguage: "డిఫాల్ట్ భాషను సెట్ చేయండి",
      updateLanguageTitle: "భాషా ఎంపికలను నవీకరించండి",
      updateLanguageDescription: "మీరు మీ భాషా ఎంపికలను ఎప్పుడైనా సెట్టింగులు పేజీ ద్వారా నవీకరించవచ్చు.",
      updateLanguage: "భాషను నవీకరించండి",
      home: "హోమ్",
      features: "ఫీచర్లు",
      about: "మన గురించి",
      contact: "సంప్రదించండి",
      logo: "TekRide"
    }
  };
  